source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

target 'BYGeneralSwift' do
    pod 'SnapKit', '~> 5.0.0'
    pod 'WCDB.swift', '~> 1.0'
    pod 'SwiftState'
    pod 'Moya', '~> 15.0'
    pod 'SwiftSoup'
    pod "PromiseKit"
    
    pod "GeneralTools", :path => "../GeneralTools"
    pod "BaseControllers", :path => "../BaseControllers"
end
