source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

target 'BYGeneralSwift' do
    pod 'SnapKit', '~> 5.0.0'
    pod 'SwiftState'
    pod 'Moya', '~> 15.0'
    pod 'SwiftSoup'
    pod "PromiseKit"
    pod 'LTMorphingLabel'
    pod 'PKHUD', '~> 5.0'
    
    pod "GeneralTools", :path => "../GeneralTools"
    pod "BaseControllers", :path => "../BaseControllers"
    pod "SwiftFormatter", :path => "../SwiftFormatter"
end
 
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
