source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

inhibit_all_warnings!

target 'BYGeneralSwift' do
    use_frameworks!

    pod 'WCDB.swift', '~> 1.0'
    pod 'SwiftState'
    pod 'Moya', '~> 15.0'

end
